import type { Task } from "./types";

export const SAMPLE_TASKS: Task[] = [
  {
    id: "task-1",
    name: "Q2 Product Roadmap",
    startDate: "2026-03-10",
    endDate: "2026-06-28",
    status: "In-Progress",
    complexity: "High",
    tags: ["strategy", "product"],
  },
  {
    id: "task-2",
    name: "Annual Budget Review",
    startDate: "2026-01-05",
    endDate: "2026-02-14",
    status: "Complete",
    complexity: "High",
    tags: ["finance"],
  },
  {
    id: "task-3",
    name: "Conference Speaking Prep",
    startDate: "2026-09-01",
    endDate: "2026-10-15",
    status: "Planned",
    complexity: "High",
    tags: ["speaking", "marketing"],
  },
  {
    id: "task-4",
    name: "Sprint 14 Planning",
    startDate: "2026-06-02",
    endDate: "2026-06-20",
    status: "In-Progress",
    complexity: "Medium",
    tags: ["engineering"],
  },
  {
    id: "task-5",
    name: "Design System Audit",
    startDate: "2026-07-01",
    endDate: "2026-08-15",
    status: "Planned",
    complexity: "Medium",
    tags: ["design", "ui"],
  },
  {
    id: "task-6",
    name: "Team Offsite Logistics",
    startDate: "2026-05-12",
    endDate: "2026-06-05",
    status: "In-Progress",
    complexity: "Medium",
    tags: ["ops"],
  },
  {
    id: "task-7",
    name: "Weekly Standup Notes",
    startDate: "2026-06-16",
    endDate: "2026-06-20",
    status: "Planned",
    complexity: "Low",
    tags: ["meetings"],
  },
  {
    id: "task-8",
    name: "Inbox Zero Session",
    startDate: "2026-06-21",
    endDate: "2026-06-21",
    status: "Planned",
    complexity: "Low",
    tags: ["admin"],
  },
  {
    id: "task-9",
    name: "Gym & Recovery Block",
    startDate: "2026-06-19",
    endDate: "2026-06-22",
    status: "In-Progress",
    complexity: "Low",
    tags: ["health"],
  },
];
